### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by basmith7** [lorilan/dnd5_dm_db#1]
I guess reddit didn't like the idea very much. 

```
[info] Loading project definition from C:\Users\xxx\Desktop\dnd5_dm_db-master\project
[info] Set current project to dnd5-dm-db (in build file:/C:/Users/xxx/Desktop/dnd5_dm_db-master/)
java.lang.RuntimeException: env var SHELL not defined
    at scala.sys.package$.error(package.scala:27)
    at DnDBuild$.varDecl(DnDBuild.scala:33)
    at DnDBuild$$anonfun$root$14.apply(DnDBuild.scala:79)
    at DnDBuild$$anonfun$root$14.apply(DnDBuild.scala:74)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
[error] (*:printClassPathFile) env var SHELL not defined
[error] Total time: 0 s, completed Oct 20, 2015 12:41:51 PM
```

**Comment by lorilan** [comment]
I did the start script for linux. I do not not how to code in window shell. Anyway I added the sbt native packager (http://www.scala-sbt.org/sbt-native-packager/). You can package it with the universal:packageZipTarball command. It will create a windows starting script. You just need to set the correct path in the conf/application.ini file.

Here is a the bin packaged : https://drive.google.com/file/d/0B_-s9coDfKnLSWo5VGRablk0VW8

I have not tried it with windows but if you do, let me know the result
